/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virginiaprivacy;

public class detectorJNI {
  public final static native String get_serialized_frontal_faces();
  public final static native long get_frontal_face_detector();
  public final static native long new_CopDetector();
  public final static native int CopDetector_countFaces(long jarg1, CopDetector jarg1_, String jarg2);
  public final static native int CopDetector_totalRuntime(long jarg1, CopDetector jarg1_);
  public final static native int CopDetector_numPolices(long jarg1, CopDetector jarg1_);
  public final static native void CopDetector_createPolice(long jarg1, CopDetector jarg1_, String jarg2, String jarg3);
  public final static native void CopDetector_save(long jarg1, CopDetector jarg1_);
  public final static native void CopDetector_load(long jarg1, CopDetector jarg1_);
  public final static native String CopDetector_getNameFromFile(String jarg1);
  public final static native String CopDetector_identifyImage(long jarg1, CopDetector jarg1_, String jarg2);
  public final static native String CopDetector_getCopName(long jarg1, CopDetector jarg1_, int jarg2);
  public final static native void delete_CopDetector(long jarg1);
}
